-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 15:42:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema puro_kitchen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema puro_kitchen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puro_kitchen` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `puro_kitchen` ;

-- -----------------------------------------------------
-- Table `puro_kitchen`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`customers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `contact` INT(11) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`deliveries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `order_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`delivery_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`delivery_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dmi` INT(11) NULL DEFAULT NULL,
  `ingredient_name` VARCHAR(45) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `delivery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_allergies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_allergies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_allergy_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_allergy_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `allergy_id` INT(11) NULL DEFAULT NULL,
  `ingredient_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_equipment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `capacity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_equipment_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_equipment_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ingredient_id` INT(11) NULL DEFAULT NULL,
  `equipment_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `k` DECIMAL(4,2) NULL DEFAULT NULL,
  `c` DECIMAL(4,2) NULL DEFAULT NULL,
  `p` DECIMAL(4,2) NULL DEFAULT NULL,
  `f` DECIMAL(4,2) NULL DEFAULT NULL,
  `s` DECIMAL(4,2) NULL DEFAULT NULL,
  `cost` DECIMAL(4,2) NULL DEFAULT NULL,
  `measurement` INT(11) NULL DEFAULT NULL,
  `volume` INT(11) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `cooktime` INT(20) NULL DEFAULT NULL,
  `preptime` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_meal_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_meal_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `meal_id` INT(11) NULL DEFAULT NULL,
  `ingredient_id` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_meals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_plans` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(5,2) NULL DEFAULT NULL,
  `meal_count` INT(11) NULL DEFAULT NULL,
  `shake_count` INT(11) NULL DEFAULT NULL,
  `snack_count` INT(11) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_shake_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_shake_ingredients` (
  `id` INT(11) NOT NULL,
  `shake_id` INT(11) NULL DEFAULT NULL,
  `indgredient_id` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_shakes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_shakes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`lu_snacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`lu_snacks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puro_kitchen`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puro_kitchen`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `cost` INT(20) NULL DEFAULT NULL,
  `payment_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
